### ISSUE TITLE
ValueError: kth(=112) out of bounds (103)

### ISSUE THREAD

**Issue by LiulingZhou** [pysal/mgwr#111]
This error occurs when GWR operation is performed after collinearity of data is removed. What should I do? Thank you!

`Traceback (most recent call last):
  File "src/gui.py", line 1004, in runGWR
  File "mgwrlib/mgwr/sel_bw.py", line 315, in search
  File "mgwrlib/mgwr/sel_bw.py", line 335, in _bw
  File "mgwrlib/mgwr/search.py", line 60, in golden_section
  File "mgwrlib/mgwr/sel_bw.py", line 325, in <lambda>
  File "mgwrlib/mgwr/gwr.py", line 332, in fit
  File "multiprocessing/pool.py", line 266, in map
  File "multiprocessing/pool.py", line 644, in get
ValueError: kth(=112) out of bounds (103)`

**Comment by Ziqi-Li** [comment]
Hi @LiulingZhou: I wonder if this is solved, if not, could you share a copy of your data? It is most likely a data-related issue.

**Comment by LiulingZhou** [comment]
> 

Hello, I have sent the data to your email with relevant instructions. Thank you. 
Looking forward to your reply.
